# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeanswer',
            name='status',
            field=models.IntegerField(default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AddField(
            model_name='likequestion',
            name='status',
            field=models.IntegerField(default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
