# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0003_auto_20170217_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questions',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432'),
        ),
    ]
